# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift

use_frameworks!

target ‘MovieList’ do

pod 'Alamofire'
pod 'SVProgressHUD'
pod 'TPKeyboardAvoiding'
pod 'ScrollTo'
pod 'ActionSheetPicker-3.0'
pod 'AlamofireImage', '~> 3.3'
pod 'ReachabilitySwift'
pod 'Firebase/Core'
pod 'Firebase/RemoteConfig'

end
